### ISSUE TITLE
BindableLayout for FlexLayout?

### ISSUE THREAD

**Issue by lochidev** [Dreamescaper/BlazorBindings.Maui#128]
`
    <FlexLayout Wrap="FlexWrap.Wrap" AlignContent="FlexAlignContent.SpaceEvenly"
        JustifyContent="FlexJustify.SpaceEvenly">
            @foreach (var list in Config.Memes)
            {
                foreach (var meme in list)
                {
                    <VerticalStackLayout Padding="new Thickness(5,5,5,5)"  
                        Spacing="5" BackgroundColor="Config.ColorList[RandomNumberGenerator.GetInt32(0, Config.ColorList.Count)]"
                        WidthRequest="100" HeightRequest="100">
                        <Label Text=@meme TextColor="Config.PageBgColor"/>
                        <Button OnClick="async() => await PlaySoundAsync(meme)" BackgroundColor="Config.Primary" Text="PLAY"/>
                    </VerticalStackLayout>
                }
            }
    </FlexLayout>`

Hi,
I'm trying to fit a lot of stacklayouts into a flexlayout and it takes a quite a while to load. Anyway I could use an observable collection with bindable layout?

**Comment by Dreamescaper** [comment]
BindableLayout is not really applicable for Blazor diff approach. Maybe it is possible to make it work, but it doesn't make much sense.

Still, while Blazor diff-ing had some perf overhead, it should more cause any noticeable effect in most cases.
Have you tried implementing it with xaml and BindableLayout, does it work faster? How many items to you have there btw?

**Comment by Dreamescaper** [comment]
Btw, this part will probably cause issues:
>BackgroundColor="Config.ColorList[RandomNumberGenerator.GetInt32(0, Config.ColorList.Count)]"

It will probably change the color on any interaction.

You can either store that color per meme somehow, or extract Meme component separately (probably a better approach).

**Comment by lochidev** [comment]
Hi, I fixed this by switching over to shell. Was using tabbedpage and was confused 😂 Amazing project btw, loving it!
