### ISSUE TITLE
Question: Fluent data grid

### ISSUE THREAD

**Issue by mrpmorris** [Dreamescaper/BlazorBindings.Maui#130]
Is there any way to use the Microsoft Fluent Data Grid?

**Comment by Dreamescaper** [comment]
You won't be able to use it directly, because it is a web control, not a MAUI control.
Same as for [MAUI Blazor Hybrid](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui), you can use BlazorWebView to host web controls, if you need that.

**Comment by mrpmorris** [comment]
Thanks! I was hoping there were native MAUI controls for them.
