### ISSUE TITLE
Multiple Carousel and HttpClient

### ISSUE THREAD

**Issue by cornelhuman** [Dreamescaper/BlazorBindings.Maui#135]
Great work on the mobile blazor bindings!

I seem to have a strange issue when using multiple carousels in a page.

In my example I have 2 carousels and they work as expected, but when I do a HttpRequest in the page the second carousel breaks, so it cant swipe left or right. This is for IOS and gives the same behaviour in the simulator and on my iphone.

The http request does not update anything in the example, but I would like to pull data using a get request and then populate multiple carousels in the same page.

Any ideas as to what may be going wrong?

https://github.com/cornelhuman/newtest

If I comment out await GetData(); in the MainPage.razor it works as expected.

**Comment by Dreamescaper** [comment]
Thanks for kind words!
I've tried to reproduce the issue from your repro, but failed to do so. Could you provide a screen recording?
Also, could you check whether it's iOS specific? Does it reproduce on Android emulator?

**Comment by cornelhuman** [comment]
I have made a recording. It is for IOS and happens on my iphone simulators, also on my personal Iphone SE and 14 Pro phones.

https://youtu.be/EP_8W28uxPE

If I comment the call to GetData() it works ;)

I will do an Android test and let you know.

Thank you

**Comment by cornelhuman** [comment]
I have played around with using a CollectionView to host the CarouselViews, and that works as expected on my IOS simulator. The above is still a strange issue.... But for the moment I can experiment with the CarouselView.
