### ISSUE TITLE
AbsoluteLayout doesn't work.

### ISSUE THREAD

**Issue by AmirImam** [Dreamescaper/BlazorBindings.Maui#140]
Hi
I am trying to use AbsoluteLayout but it doesn't work. 
**My code**:
![image](https://github.com/Dreamescaper/BlazorBindings.Maui/assets/26382843/87329e93-d597-448a-8952-f5aad81f7a26)

**BlazorBindings.Maui.Templates** version 1.0.1

**Comment by Dreamescaper** [comment]
What is the actual behavior though?

**Comment by AmirImam** [comment]
> What is the actual behavior though?

What do you mean by actual behavior?

**Comment by Dreamescaper** [comment]
I mean - _how_ it doesn't work? What behavior do you expect, and what do you actually see?

I don't think your LayoutBounds are correct. Currently you have a Box with a Size=1x1. With a CornerRadius=10 it's probably not visible at all.

**Comment by AmirImam** [comment]
> I mean - _how_ it doesn't work? What behavior do you expect, and what do you actually see?
> 
> I don't think your LayoutBounds are correct. Currently you have a Box with a Size=1x1. With a CornerRadius=10 it's probably not visible at all.

I am sorry it's my mistake. I found the issue in the LayoutBounds as you said. Thank you.
