### ISSUE TITLE
MAUI application in release mode crashing on navigate

### ISSUE THREAD

**Issue by Denny09310** [Dreamescaper/BlazorBindings.Maui#151]
I created a basic demo application that works fine in debug mode but crashes during page navigation in release mode.

I've attached the [crash log](https://github.com/user-attachments/files/17526610/log.txt) from Android and the [project files](https://github.com/user-attachments/files/17526622/App1.zip) in case they're needed for troubleshooting.

The specific code where the issue occurs is within PostView.razor:

```csharp
private Task NavigateToDetailsAsync()
{
    return Navigation.NavigateToAsync($"/details/{Post.Id}");
}
```

**Comment by Denny09310** [comment]
Ok probably found out the problem. The AOT and Trimming is causing this issue, it converts the property removing the setter

```csharp
// Before
public NavigationManager NavigationManager { get; set; }

// After
public NavigationManager NavigationManager { get; }
```

This causes the dependency injector to give the error found in the crashlog. I've solved this issue inside my project using the combination of TrimmingRootDescriptors

```
<ItemGroup>
	<TrimmerRootDescriptor Include="Roots.xml" />
</ItemGroup>
```

```
<linker>
	<assembly fullname="Microsoft.AspNetCore.Components" preserve="all" />
</linker>
```

With the file Roots.xml to avoid entirely trimming the Microsoft.AspNetCore.Components package. Probably is worth doing this even inside the nuget package.

**Comment by Dreamescaper** [comment]
Thanks a lot for your research! 
I assume this is iOS?

**Comment by Dreamescaper** [comment]
Thanks a lot for your research! 
I assume this is iOS?

UPDATE: Ok, I see that's Android...

**Comment by Denny09310** [comment]
> Thanks a lot for your research! I assume this is iOS?

Sorry I was in a hurry I didn't mention that is android, but i think IOS suffer this issue as well

**Comment by Dreamescaper** [comment]
Yeah, I thought it's iOS, as Android doesn't use AOT compilation with MAUI.
But maybe it does use trimming.
