### ISSUE TITLE
Events naming - does it make sense?

### ISSUE THREAD

**Issue by Dreamescaper** [Dreamescaper/BlazorBindings.Maui#43]
Currently for all the eventCallback we use the naming with "On" prefix (e.g. Scrolled -> OnScrolled, Clicked -> OnClick). I'm not really sure why it was made this way. Does is make any sense? Would it be better to use the same name as Maui events?

**Comment by marinasundstrom** [comment]
I think that is the convention. It makes it easier to distinguish props for EventCallbacks from normal props.
