### ISSUE TITLE
Are threre any plans to support Effects and Behavior ?

### ISSUE THREAD

**Issue by le-nn** [Dreamescaper/BlazorBindings.Maui#46]
Thank you for Amazing project !

Currently, we should access to  Shadows, Behaviors, and Effects via @ref and Element.NativeControl. 
Any plans to implement it as an Attribute on Blazor element?

**Comment by Dreamescaper** [comment]
> Thank you for Amazing project !

Thanks!
Shadows are relatively easy to add, I'll try to add them in the next couple of days.

As for behaviors and effects - could you describe your use cases? Which behaviors, for which controls?

I'm not sure how to support behaviors, as they are a bit foreign to Blazor. It would look nice to define them in markup, as you would do with XAML, but with Blazor that would require to create Blazor component class for every possible behavior, and it doesn't seems like a great idea.

Is that ok simply to expose that as `Behavior[]` property? So that would look smth like that?
```razor
<Entry Behaviors="_entryBehaviors" />

@code {
    private Behavior[] _entryBehaviors = new[] { new MyFirstBehavior(), new MySecondBehavior() };
}
```

Alternative option I thought about is to create some generic component to hold behavior value, so it would look like this:
```razor
<Entry>
    <Behaviors>
        <BehaviorItem Type="MyFirstBehavior" />
        <BehaviorItem Type="MySecondBehavior" />
    </Behaviors>
</Entry>
```

WDYT?

**Comment by Dreamescaper** [comment]
As for Effects - all the above still applies, but additionally MAUI team doesn't recommend using them at all (they've only left them in MAUI to make transaction from XF easier), so I'm not sure if it makes sense to add the support for them at all here.

Again, please let me know your thoughts and use case.

**Comment by le-nn** [comment]
Thanks for kind replying.
 
Here is my usecase.

### case 1

I just wanted a declarative animation like the following library or react/flutter/swiftui.

https://github.com/jsuarezruiz/MauiAnimation

My team uses React a lot and recently started using Blazor, so I'm not familiar with Blazor or MAUI.
So sorry if I didn't come up with the best idea for Blazor and maybe asked a stupid question.
For HTML with CSS Transitions it's easy.

BlazorBindings needs to call methods like ```Element.NativeControl.ScaleTo(...)```.

I was looking for a way to make it easier, and I thought I would use Behavior

### case 2

I tried to implement custom plat form effect such as the Windows mouse pointer, Context menus , but RC1 comes with Pointer Gesture, so it will be resolved.

Thanks.

**Comment by Dreamescaper** [comment]
@le-nn 
I've published a new release with Shadows support. You can read notes [here](https://dev.to/dreamescaper/blazorbindingsmaui-preview-9-4iob).

**Comment by Dreamescaper** [comment]
As for behavior, I still don't really understand the use case :(

Could you give a XAML example how would you replace `.ScaleTo()` (invoked on some condition, I suppose) with a behavior?

**Comment by Dreamescaper** [comment]
I have merged the support for Behaviors, it will be included in the next release, but you can try it with the [nightly release](https://dreamescaper.github.io/MobileBlazorBindingsDocs/maui-blazor-bindings/contribute/nightly-builds.html).

While no built-in behaviors are provided, you can generate bindings for the third party behaviors via [component generator](https://dreamescaper.github.io/MobileBlazorBindingsDocs/maui-blazor-bindings/advanced/custom-components.html#wrapping-maui-components).

You can take a look at the example here:
[Elements.cs](https://github.com/Dreamescaper/BlazorBindings.Maui/blob/main/samples/ThirdPartyControlsSample/Properties/Elements.cs)
[CommunityToolkitBehaviors.razor](https://github.com/Dreamescaper/BlazorBindings.Maui/blob/main/samples/ThirdPartyControlsSample/Pages/CommunityToolkitBehaviors.razor)

**Comment by Dreamescaper** [comment]
I am not sure whether it makes any sense to support Effects. While they are still supported for compatibility, MAUI guys do not recommend using them.

**Comment by Dreamescaper** [comment]
1.0 with Behaviors support is released to nuget, so I'm closing the issue.
Please log a separate issue if you need the support for Effects.
