### ISSUE TITLE
Any plans to support HTML and CSS?

### ISSUE THREAD

**Issue by mhrastegari** [Dreamescaper/BlazorBindings.Maui#50]
### Summary
Is there any plans (or maybe ways) to mix and use XAML and HTML/CSS?

### Screenshot
![Screenshot (1503)](https://user-images.githubusercontent.com/42671084/192490486-5269cbf1-9043-4f54-b65a-8a56949f60eb.png)

**Comment by Dreamescaper** [comment]
You can't put html content directly in native components, but you can use BlazorWebView for that.
I've pushed a small sample to 'blazor-web-view-sample' branch.
https://github.com/Dreamescaper/BlazorBindings.Maui/tree/blazor-web-view-sample/samples/HybridSample

**Comment by CeSun** [comment]
> You can't put html content directly in native components, but you can use BlazorWebView for that. I've pushed a small sample to 'blazor-web-view-sample' branch. https://github.com/Dreamescaper/BlazorBindings.Maui/tree/blazor-web-view-sample/samples/HybridSample

Is there a project template for hybrid app? Or a guide for adding hybrid functionality to an existing project?

**Comment by mhrastegari** [comment]
Yes there is!
Our friend made a perfect template that you could have Web and App project both in one solution

https://bitplatform.dev/todo-template/getting-started

**Comment by Dreamescaper** [comment]
I'm closing the issue as answered, let me know if you have any more questions.
