### ISSUE TITLE
Error on adding component to an element

### ISSUE THREAD

**Issue by AmirImam** [Dreamescaper/BlazorBindings.Maui#57]
Hi
This line of code throws an exception
```
[Inject]
private MauiBlazorBindingsRenderer Renderer { get; set; }

    protected override async void OnAfterRender(bool firstRender)
    {
        if (firstRender is true)
        {
            ContentPage page = new() { Title = "Ref" };
            await Renderer.AddComponent<MainPage>(page); //Error here
        }
    }
```
Exception is
![image](https://user-images.githubusercontent.com/26382843/194806650-7dbae729-531b-490e-9ffa-49662e66c585.png)

MainPage is a ContentView
I tried to make it a ContentPage but it throws the same error
I tried this on windows & android

**Comment by Dreamescaper** [comment]
Yeah, seems like I've accidentally broken it for other controls (apart from Application). I'll try to fix it soon.

I'm wondering though - what is your use case? Why do you add content to a page inside of other Blazor component?

**Comment by AmirImam** [comment]
I want to use **NavigationPage** to navigate between pages, and I want to set this **NavigationPage** to the **Details** of a **FlyoutPage**. I have always designed my classic XF apps like this, and I want to try it here

**Comment by Dreamescaper** [comment]
I see. 

As a temporary workaround (until I fix this issue), you can retrieve a page via smth like this (your main page should have ContentPage as a root element):
```csharp
        var rootContainer = new RootContainerHandler();
        await Renderer.AddComponent<MainPage>(rootContainer);
        var page = (MC.Page)rootContainer.Elements[0];
```

Also, you can take a look at a FlyoutPage sample, it makes it work without Renderer interaction:
https://github.com/Dreamescaper/BlazorBindings.Maui/blob/main/samples/FlyoutPageSample/Views/MainPage.razor .

**Comment by AmirImam** [comment]
> I see.
> 
> As a temporary workaround (until I fix this issue), you can retrieve a page via smth like this (your main page should have ContentPage as a root element):
> 
> ```cs
>         var rootContainer = new RootContainerHandler();
>         await Renderer.AddComponent<MainPage>(rootContainer);
>         var page = (MC.Page)rootContainer.Elements[0];
> ```
> 
> Also, you can take a look at a FlyoutPage sample, it makes it work without Renderer interaction: https://github.com/Dreamescaper/BlazorBindings.Maui/blob/main/samples/FlyoutPageSample/Views/MainPage.razor .

Thank you, this workaround worked fine.
I think that I can't test **FlyoutMenuPage** yet, did you release it?
